### ISSUE TITLE
Collaboration for a GUI batch-convert tool?

### ISSUE THREAD

**Issue by kangalio** [lrfasd/lrfasd.github.io#1]
Hello lrfasd,

I'm an enthusiastic VSRG rhythm gamer, active member and contributor of the Etterna community, and I'd be interested in collaborating with you to produce a GUI wrapper around this conversion code to allow batch-conversion of chart files.

I've peeked at the javascript code embedded in the newest [demo html](https://github.com/lrfasd/lrfasd.github.io/blob/master/rmstZ/rmstZ_20200403.html). Now I have a rough understanding of the basic code structure, and would like to try and build some GUI desktop tool on top to get the full potential out of this magnificent conversion code.

However, I think it is smarter to work _together_ with you, instead of secretly extracting and un-obfuscating your code. Therefore, I'd love to know if you're interested in a project like this?

(这是自动翻译的)

你好lrfasd。

我是一个热衷于VSRG节奏游戏的玩家，也是Etterna社区的活跃成员和贡献者，我很有兴趣与你合作，围绕这段转换代码制作一个GUI封装器，以实现歌曲文件的批量转换。

我已经偷看了最新的演示html中嵌入的javascript代码。现在，我已经大致了解了基本的代码结构，并想尝试在上面搭建一些GUI桌面工具，以充分发挥这段华丽的转换代码的潜力。

不过，我认为与你合作，而不是偷偷地提取和解密你的代码，是比较明智的做法。因此，我很想知道你是否对这样的项目感兴趣？

**Comment by lrfasd** [comment]
不好意思现在才看到你的留言。最近实在是太没时间了，以至于本项目都一直没更新。
你的提案很好，但是我很久没开发GUI桌面工具，如何写代码我几乎忘了。
前不久我在某个讨论群组中有看到有人引用该项目代码开发了桌面工具实现了批量转换，虽然是初步阶段，简陋了一些，而且不清楚他是以什么默认选项转换的，但是我想不起他是谁了。
如果你要引用我的代码，我很乐意。如果有什么需要交流的，联系lrfasd@163.com我可能会回复得及时一些。
以我目前的情况，如果我有时间写代码，我希望能将时间用在更新本项目上，毕竟还有很多想法还没有实现。至于你提案的项目，最好是以你为主来开发。
（我英语不是很好，为了表达准确，用中文来回复你，请使用自动翻译功能）
