### ISSUE TITLE
rmstZ读入PMS时第6，7，8，9轨没有音符

### ISSUE THREAD

**Issue by loader3229** [lrfasd/lrfasd.github.io#3]
rmstZ读入PMS时第6，7，8，9轨没有音符，就算被打开的PMS使用PMS播放器打开时第6，7，8，9轨有音符

PMS的第6轨为#xxx22（第6轨的长音符为#xxx62）
PMS的第7轨为#xxx23（第7轨的长音符为#xxx63）
PMS的第8轨为#xxx24（第8轨的长音符为#xxx64）
PMS的第9轨为#xxx25（第9轨的长音符为#xxx65）

**Comment by lrfasd** [comment]
已修复，会在最新版本更新
