### ISSUE TITLE
ampedE (Kar Extractor)

### ISSUE THREAD

**Issue by muhammadfarhan26** [lrfasd/lrfasd.github.io#7]
Hi irfasd I'm currently very interested in being able to extract .kar files from the game getamped. Then I saw you shared a kar extractor for getamped. But the link doesn't work, maybe if you can re-upload it I will really appreciate it and it will help me a lot, thank you.

您好 irfasd 我目前对能够从 getamped 游戏中提取 .kar 文件非常感兴趣。 然后我看到你分享了一个用于 getamped 的 kar 提取器。 但是链接失效了，如果你能重新上传一下，我会很感激的，这对我有很大帮助，谢谢。

**Comment by muhammadfarhan26** [comment]
Also where can i found all ampedT Plugin?

我在哪里可以找到所有 ampedT 插件？

**Comment by lrfasd** [comment]
ampedT Plugin is not Public

**Comment by lrfasd** [comment]
kar extractor technology cannot be disclosed
